### ISSUE TITLE
It's doesn't work

### ISSUE THREAD

**Issue by X-n3t** [nyxgeek/o365recon#2]
From the official o365 webpage the credentials are valids.

From your script I have problems:
![imagen](https://user-images.githubusercontent.com/52056830/96724900-9af74400-13b0-11eb-8011-0588daea2728.png)

do you know the reason?

**Comment by nyxgeek** [comment]
It's just calling the msol-connect powershell script. If you're getting the login prompt, you're dealing directly with microsoft auth. I would try just the Connect-MsolService commandlet on its own to verify (that is all the script does to auth). https://docs.microsoft.com/en-us/powershell/module/msonline/connect-msolservice?view=azureadps-1.0
