### ISSUE TITLE
Only internally

### ISSUE THREAD

**Issue by alex-milla** [nyxgeek/o365recon#3]
I observe that this script does not work externally if you have an MFA enabled.

```
                        Checking for MsOnline Module ...                DONE
                        Connecting to O365  ... Could not connect to O365. Have you run Install-Module MsOnline ?
Exception: C:\Temp\o365recon-master\o365recon.ps1:76
Line |
  76 |      Connect-MsolService -ErrorAction Stop -Credential $userauth > $nu …
     |      ~~~~~~~~~~~~~~~~~~~
     | The term 'Connect-MsolService' is not recognized as the name of a cmdlet, function, script file, or
     | operable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.
```

If I run inside my network with valid credentials it does extract all the information from O365.

It will also not work if using an admin account with double MFA, as it will ask for additional verification.

I understand that this script will work externally for credentials that do not have MFA enabled.

:)

**Comment by nyxgeek** [comment]
Interesting -- my mfa works with it. The first attempt fails (because it is trying user/pass only), and then it should fall back to modern login where it will complete the mfa. Let me dig into this some more and see if there's a better way to prompt for auth in case of MFA.

**Comment by nyxgeek** [comment]
I redid the login logic. Check it out and see if that fixes the issue for you.

**Comment by alex-milla** [comment]
Great job! 😀

Now it let me authenticate and skipped the conditional that I can only connect from a business account.

The only protection left is when the notification (call, push) is received.

**Comment by nyxgeek** [comment]
Closing out after updating login logic.
