### ISSUE TITLE
Connect-AzureAD is not recognized as a name of a cmdlet on macOS

### ISSUE THREAD

**Issue by Techbrunch** [nyxgeek/o365recon#4]
I wanted to see if the script works on macOS but it doesn't:

```
PS /Users/xxx/Documents/github/o365recon> .\o365recon.ps1 -azure
Connecting to Microsoft services:
			Checking for MsOnline Module ... 		DONE
			Checking for AzureAD Module ... 		DONE
			Connecting to AzureAD with Connect-AzureADCould not connect to AzureAD.
Exception: /Users/xxx/Documents/github/o365recon/o365recon.ps1:56
Line |
  56 |          Connect-AzureAD -Credential $userauth > $null
     |          ~~~~~~~~~~~~~~~
     | The term 'Connect-AzureAD' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
```

To run the script I first installed powershell using:

```
brew install --cask powershell
```

**Comment by ahrib** [comment]
I have the same issue. Attempting to study for AZ-104 certification on Mac

environment:
CPU: Apple M1 Pro
OS: macOS Monterey version 12.2.1
Powershell version: 7.2.1

replication steps:
```
Install-Module -Name Az -Force
Install-Module -Name AzureAD -Force
Connect-AzureAD
```

result:
> The term 'Connect-AzureAD' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again


additional diagnosis steps:
running `Import-Module AzureAD` results in the message:
> Import-Module: The current processor architecture is: MSIL. The module '_REDACTED_/.local/share/powershell/Modules/AzureAD/2.0.2.140/AzureAD.psd1' requires the following architecture: Amd64.

A note that _REDACTED_ contained my username and was manually redacted by myself.

**Comment by nyxgeek** [comment]
This is an issue with PowerShell for Mac OS and the Microsoft commandlets not working cross-platform (I saw similar reports for Linux). If you do some googling for "powershell mac connect-azuread" you'll see others with the same problem, no solution that I was able to find. The problem seems to go back to 2017, and if Microsoft hasn't fixed it yet, I wouldn't hold my breath.

Easiest fix: use Windows. VirtualBox is a good, free solution.

**Comment by ahrib** [comment]
apologies @nyxgeek I raised the issue in the wrong repo, thought I was adding to powershell.

> Easiest fix: use Windows. VirtualBox is a good, free solution.

A note for others experiencing this issue x86/x64 virtualisation does not work on M1 hardware via vitualbox, vmware, & parallels only viable solution is to use a different computer or a cloud vm.
