### ISSUE TITLE
Unable to get device info

### ISSUE THREAD

**Issue by y0k4i-1337** [nyxgeek/o365recon#5]
During execution, the script hangs a while on "Group Membership" step and then, when it goes to "Device Info" part, I am getting the error on the image.
![image](https://user-images.githubusercontent.com/7395296/155339035-dfd92968-ee51-4a79-9b79-256c73a933ac.png)

I tried to run more than once and every time the issue occurs. If I run the command "Get-MsolDevices -All" manually, it works though.

Any idea?

**Comment by shivasbalakrishnan** [comment]
> During execution, the script hangs a while on "Group Membership" step and then, when it goes to "Device Info" part, I am getting the error on the image.
> 
> ![image](https://user-images.githubusercontent.com/7395296/155339035-dfd92968-ee51-4a79-9b79-256c73a933ac.png)
> 
> 
> 
> I tried to run more than once and every time the issue occurs. If I run the command "Get-MsolDevices -All" manually, it works though.
> 
> 
> 
> Any idea?

Hello before connecting to this command you need to connect-Msolservice

**Comment by shivasbalakrishnan** [comment]
Or you can connect-AzureADDevice - All

**Comment by shivasbalakrishnan** [comment]
Get-MsolDevice (MSOnline)
Get-MobileDevice (EXO)
Get-AzureADDevice (AzureAD)
